# Generated by Django 3.1.2 on 2020-11-22 21:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stopgameheadline',
            old_name='title',
            new_name='desc',
        ),
    ]
