# Generated by Django 3.1.2 on 2020-11-24 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0003_auto_20201122_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ignheadline',
            options={'verbose_name': 'Статья IGN', 'verbose_name_plural': 'Статьи IGN'},
        ),
        migrations.AlterModelOptions(
            name='stopgameheadline',
            options={'verbose_name': 'Статья StopGame', 'verbose_name_plural': 'Статьи StopGame'},
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author',
                                             to=settings.AUTH_USER_MODEL)),
                ('headline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments',
                                               to='games.stopgameheadline')),
            ],
        ),
    ]
